/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DS-Digital24.c                                        *
* Font:        DS-Digital                                            *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3C (60)                                     *
* Character enabled:   0x2C (44)                                     *
* Character enabled:   0x2E (46)                                     *
* Character disabled:  0x2E (46)                                     *
* Character enabled:   0x25 (37)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0025[ 30] = { /* code 0025, PERCENT SIGN */
  __XXX___,_XX_____,
  XX__XX__,_X______,
  XX__XX__,XX______,
  XX__XX_X,X_______,
  XX__XX_X,X_______,
  __XXX_XX,________,
  ______X_,________,
  _____XX_,________,
  _____X__,XXX_____,
  ____XX_X,XX_X____,
  ___XX__X,___X____,
  ___XX__X,___X____,
  __XX___X,___X____,
  __XX___X,XX_X____,
  ________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_002C[  3] = { /* code 002C, COMMA */
  XX______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0030[ 30] = { /* code 0030, DIGIT ZERO */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_______,X_______,
  ________,________,
  X_______,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0031[ 15] = { /* code 0031, DIGIT ONE */
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  ________,
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0032[ 30] = { /* code 0032, DIGIT TWO */
  _XXXXXXX,X_______,
  __XXXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ________,X_______,
  _XXXXXXX,________,
  XXXXXXXX,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  X_XXXXXX,________,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0033[ 30] = { /* code 0033, DIGIT THREE */
  XXXXXXXX,X_______,
  _XXXXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ________,X_______,
  _XXXXXX_,________,
  _XXXXXX_,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _XXXXXX_,X_______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0034[ 30] = { /* code 0034, DIGIT FOUR */
  X_______,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_______,X_______,
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0035[ 30] = { /* code 0035, DIGIT FIVE */
  XXXXXXXX,________,
  XXXXXXXX,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  X_______,________,
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXXXX,X_______,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0036[ 30] = { /* code 0036, DIGIT SIX */
  XXXXXXXX,________,
  XXXXXXXX,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  X_______,________,
  _XXXXXXX,________,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_XXXXXX,X_______,
  _XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0037[ 30] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  _XXXXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ________,X_______,
  ________,________,
  ________,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0038[ 30] = { /* code 0038, DIGIT EIGHT */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_______,X_______,
  _XXXXXXX,________,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_XXXXXX,X_______,
  _XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_0039[ 30] = { /* code 0039, DIGIT NINE */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_______,X_______,
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXXXX,X_______,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_003A[ 13] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_003B[ 15] = { /* code 003B, SEMICOLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital24_003D[  5] = { /* code 003D, EQUALS SIGN */
  _XXXXXX_,
  _XXXXXX_,
  ________,
  _XXXXXX_,
  _XXXXXX_};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDSDigital24_CharInfo[15] = {
   {  12,  15,   1,   5,  15, acGUI_FontDSDigital24_0025 } /* code 0025, PERCENT SIGN */
  ,{   2,   3,   1,  19,   4, acGUI_FontDSDigital24_002C } /* code 002C, COMMA */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0030 } /* code 0030, DIGIT ZERO */
  ,{   2,  15,   2,   5,   6, acGUI_FontDSDigital24_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0033 } /* code 0033, DIGIT THREE */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0035 } /* code 0035, DIGIT FIVE */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0037 } /* code 0037, DIGIT SEVEN */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0038 } /* code 0038, DIGIT EIGHT */
  ,{   9,  15,   1,   5,  12, acGUI_FontDSDigital24_0039 } /* code 0039, DIGIT NINE */
  ,{   2,  13,   2,   7,   5, acGUI_FontDSDigital24_003A } /* code 003A, COLON */
  ,{   2,  15,   2,   7,   5, acGUI_FontDSDigital24_003B } /* code 003B, SEMICOLON */
  ,{   8,   5,   1,  10,  10, acGUI_FontDSDigital24_003D } /* code 003D, EQUALS SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital24_Prop4 = {
   0x003D /* first character */
  ,0x003D /* last character  */
  ,&GUI_FontDSDigital24_CharInfo[ 14] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital24_Prop3 = {
   0x0030 /* first character */
  ,0x003B /* last character  */
  ,&GUI_FontDSDigital24_CharInfo[  2] /* address of first character */
  ,&GUI_FontDSDigital24_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital24_Prop2 = {
   0x002C /* first character */
  ,0x002C /* last character  */
  ,&GUI_FontDSDigital24_CharInfo[  1] /* address of first character */
  ,&GUI_FontDSDigital24_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital24_Prop1 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontDSDigital24_CharInfo[  0] /* address of first character */
  ,&GUI_FontDSDigital24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDSDigital24_Prop1}
  ,20 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

