/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DS-Digital28.c                                        *
* Font:        DS-Digital                                            *
* Height:      28                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  28                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3B (59)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x25 (37)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital28;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0025[ 36] = { /* code 0025, PERCENT SIGN */
  _XXX____,___X____,
  XXXXX___,__XX____,
  X___XX__,_XX_____,
  X___XX__,XXX_____,
  X___XX__,XX______,
  X___XX_X,XX______,
  XXXXX__X,X_______,
  _XXX___X,________,
  ________,________,
  _____XX_,________,
  ____XXX_,_XXX____,
  ____XX_X,XXX_X___,
  ___XX__X,X___X___,
  ___XX__X,X___X___,
  __XX___X,X___X___,
  __XX___X,X___X___,
  __X____X,_XXXX___,
  __X_____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0030[ 36] = { /* code 0030, DIGIT ZERO */
  XXXXXXXX,XX______,
  XXXXXXXX,X_X_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  X_______,_XX_____,
  ________,________,
  X_______,__X_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  X_XXXXXX,X_X_____,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0031[ 18] = { /* code 0031, DIGIT ONE */
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  ________,
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0032[ 36] = { /* code 0032, DIGIT TWO */
  _XXXXXXX,XX______,
  __XXXXXX,X_X_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  _XXXXXXX,X_X_____,
  _XXXXXXX,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  X_XXXXXX,X_______,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0033[ 36] = { /* code 0033, DIGIT THREE */
  XXXXXXXX,X_______,
  _XXXXXXX,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,X_______,
  ________,_X______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  _XXXXXXX,XX______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0034[ 36] = { /* code 0034, DIGIT FOUR */
  X_______,________,
  XX______,__X_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XXXXXXXX,X_X_____,
  _XXXXXXX,X_______,
  ________,__X_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0035[ 36] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XX______,
  X_XXXXXX,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  __XXXXXX,X_X_____,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0036[ 36] = { /* code 0036, DIGIT SIX */
  _XXXXXXX,XX______,
  X_XXXXXX,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXXXXXXX,X_______,
  _XXXXXXX,X_______,
  X_______,__X_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  X_XXXXXX,X_X_____,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0037[ 36] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,_X______,
  ________,________,
  ________,_X______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0038[ 36] = { /* code 0038, DIGIT EIGHT */
  _XXXXXXX,XX______,
  X_XXXXXX,X_X_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XXXXXXXX,X_X_____,
  _XXXXXXX,X_______,
  X_______,__X_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  X_XXXXXX,X_X_____,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_0039[ 36] = { /* code 0039, DIGIT NINE */
  _XXXXXXX,XX______,
  X_XXXXXX,X_X_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XXXXXXXX,X_X_____,
  _XXXXXXX,X_______,
  ________,__X_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  __XXXXXX,X_X_____,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_003A[ 15] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital28_003D[  6] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,
  XXXXXXXX,
  ________,
  ________,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDSDigital28_CharInfo[14] = {
   {  13,  18,   2,   5,  17, acGUI_FontDSDigital28_0025 } /* code 0025, PERCENT SIGN */
  ,{   2,   2,   1,  21,   5, acGUI_FontDSDigital28_002E } /* code 002E, FULL STOP */
  ,{  11,  18,   1,   5,  14, acGUI_FontDSDigital28_0030 } /* code 0030, DIGIT ZERO */
  ,{   2,  18,   2,   5,   7, acGUI_FontDSDigital28_0031 } /* code 0031, DIGIT ONE */
  ,{  11,  18,   1,   5,  14, acGUI_FontDSDigital28_0032 } /* code 0032, DIGIT TWO */
  ,{  10,  18,   2,   5,  14, acGUI_FontDSDigital28_0033 } /* code 0033, DIGIT THREE */
  ,{  11,  18,   1,   5,  14, acGUI_FontDSDigital28_0034 } /* code 0034, DIGIT FOUR */
  ,{  11,  18,   1,   5,  14, acGUI_FontDSDigital28_0035 } /* code 0035, DIGIT FIVE */
  ,{  11,  18,   1,   5,  14, acGUI_FontDSDigital28_0036 } /* code 0036, DIGIT SIX */
  ,{  10,  18,   2,   5,  14, acGUI_FontDSDigital28_0037 } /* code 0037, DIGIT SEVEN */
  ,{  11,  18,   1,   5,  14, acGUI_FontDSDigital28_0038 } /* code 0038, DIGIT EIGHT */
  ,{  11,  18,   1,   5,  14, acGUI_FontDSDigital28_0039 } /* code 0039, DIGIT NINE */
  ,{   2,  15,   2,   8,   6, acGUI_FontDSDigital28_003A } /* code 003A, COLON */
  ,{   8,   6,   1,  11,  12, acGUI_FontDSDigital28_003D } /* code 003D, EQUALS SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital28_Prop4 = {
   0x003D /* first character */
  ,0x003D /* last character  */
  ,&GUI_FontDSDigital28_CharInfo[ 13] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital28_Prop3 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontDSDigital28_CharInfo[  2] /* address of first character */
  ,&GUI_FontDSDigital28_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital28_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDSDigital28_CharInfo[  1] /* address of first character */
  ,&GUI_FontDSDigital28_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital28_Prop1 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontDSDigital28_CharInfo[  0] /* address of first character */
  ,&GUI_FontDSDigital28_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital28 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,28 /* height of font  */
  ,28 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDSDigital28_Prop1}
  ,23 /* Baseline */
  ,18 /* Height of lowercase characters */
  ,18 /* Height of capital characters */
};

