/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DS-Digital30.c                                        *
* Font:        DS-Digital                                            *
* Height:      30                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  30                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3B (59)                                     *
* Character enabled:   0x2E (46)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital30;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_002E[  3] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0030[ 38] = { /* code 0030, DIGIT ZERO */
  _XXXXXXX,XXX_____,
  X_XXXXXX,XX______,
  XX_XXXXX,X__X____,
  XX______,__XX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  _X______,__X_____,
  ________,________,
  _X______,__X_____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XX______,__XX____,
  XX_XXXXX,X__X____,
  X_XXXXXX,XX______,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0031[ 38] = { /* code 0031, DIGIT ONE */
  _______X,________,
  ______XX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ______X_,________,
  ________,________,
  ______X_,________,
  ______XX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ______XX,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0032[ 38] = { /* code 0032, DIGIT TWO */
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X__X____,
  ________,__XX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XX______,
  XXXXXXXX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XX______,________,
  XX_XXXXX,X_______,
  X_XXXXXX,XX______,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0033[ 38] = { /* code 0033, DIGIT THREE */
  XXXXXXXX,XXX_____,
  _XXXXXXX,XX_X____,
  __XXXXXX,X_XX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  __XXXXXX,X_X_____,
  _XXXXXXX,XX______,
  __XXXXXX,X_X_____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  __XXXXXX,X_XX____,
  _XXXXXXX,XX_X____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0034[ 38] = { /* code 0034, DIGIT FOUR */
  X_______,________,
  XX______,___X____,
  XXX_____,__XX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  _XXXXXXX,X_X_____,
  __XXXXXX,XX______,
  __XXXXXX,X_X_____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,__XX____,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0035[ 38] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXX_____,
  X_XXXXXX,XX______,
  XX_XXXXX,X_______,
  XX______,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,X_______,
  __XXXXXX,XX______,
  __XXXXXX,XXXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,__XX____,
  ___XXXXX,X__X____,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0036[ 38] = { /* code 0036, DIGIT SIX */
  _XXXXXXX,XXX_____,
  X_XXXXXX,XX______,
  XX_XXXXX,X_______,
  XX______,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  _XXXXXXX,X_______,
  __XXXXXX,XX______,
  _XXXXXXX,X_X_____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XX______,__XX____,
  XX_XXXXX,X__X____,
  X_XXXXXX,XX______,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0037[ 38] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXX_____,
  _XXXXXXX,XX_X____,
  __XXXXXX,X_XX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,__X_____,
  ________,________,
  ________,__X_____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,__XX____,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0038[ 38] = { /* code 0038, DIGIT EIGHT */
  _XXXXXXX,XXX_____,
  X_XXXXXX,XX______,
  XX_XXXXX,X__X____,
  XX______,__XX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  _XXXXXXX,X_X_____,
  __XXXXXX,XX______,
  _XXXXXXX,X_X_____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XX______,__XX____,
  XX_XXXXX,X__X____,
  X_XXXXXX,XX______,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_0039[ 38] = { /* code 0039, DIGIT NINE */
  _XXXXXXX,XXX_____,
  X_XXXXXX,XX______,
  XX_XXXXX,X__X____,
  XX______,__XX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  XXX_____,_XXX____,
  _XXXXXXX,X_X_____,
  __XXXXXX,XX______,
  __XXXXXX,X_X_____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,__XX____,
  ___XXXXX,X__X____,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital30_003A[ 16] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDSDigital30_CharInfo[12] = {
   {   3,   3,   1,  22,   5, acGUI_FontDSDigital30_002E } /* code 002E, FULL STOP */
  ,{  12,  19,   1,   6,  15, acGUI_FontDSDigital30_0030 } /* code 0030, DIGIT ZERO */
  ,{  12,  19,   3,   6,  15, acGUI_FontDSDigital30_0031 } /* code 0031, DIGIT ONE */
  ,{  12,  19,   1,   6,  15, acGUI_FontDSDigital30_0032 } /* code 0032, DIGIT TWO */
  ,{  12,  19,   2,   6,  15, acGUI_FontDSDigital30_0033 } /* code 0033, DIGIT THREE */
  ,{  12,  19,   1,   6,  15, acGUI_FontDSDigital30_0034 } /* code 0034, DIGIT FOUR */
  ,{  12,  19,   1,   6,  15, acGUI_FontDSDigital30_0035 } /* code 0035, DIGIT FIVE */
  ,{  12,  19,   1,   6,  15, acGUI_FontDSDigital30_0036 } /* code 0036, DIGIT SIX */
  ,{  12,  19,   2,   6,  15, acGUI_FontDSDigital30_0037 } /* code 0037, DIGIT SEVEN */
  ,{  12,  19,   1,   6,  15, acGUI_FontDSDigital30_0038 } /* code 0038, DIGIT EIGHT */
  ,{  12,  19,   1,   6,  15, acGUI_FontDSDigital30_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  16,   2,   9,   7, acGUI_FontDSDigital30_003A } /* code 003A, COLON */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital30_Prop2 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontDSDigital30_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital30_Prop1 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDSDigital30_CharInfo[  0] /* address of first character */
  ,&GUI_FontDSDigital30_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital30 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,30 /* height of font  */
  ,30 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDSDigital30_Prop1}
  ,25 /* Baseline */
  ,19 /* Height of lowercase characters */
  ,19 /* Height of capital characters */
};

