/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DS-Digital48.c                                        *
* Font:        DS-Digital                                            *
* Height:      48                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  48                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x3B (59)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3D (61)                                     *
* Character enabled:   0x3D (61)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3F (63)                                     *
* Character enabled:   0x2E (46)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital48;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_002E[  5] = { /* code 002E, FULL STOP */
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0030[ 93] = { /* code 0030, DIGIT ZERO */
  _XXXXXXX,XXXXXXXX,XX______,
  X_XXXXXX,XXXXXXXX,XX_X____,
  XX_XXXXX,XXXXXXXX,X_XX____,
  XXX_XXXX,XXXXXXXX,_XXX____,
  XXXX_XXX,XXXXXXX_,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXX____,________,XXXX____,
  _X______,________,__X_____,
  ________,________,________,
  ________,________,________,
  _X______,________,__X_____,
  XXXX____,________,_XXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXX_XXX,XXXXXXX_,XXXX____,
  XXX_XXXX,XXXXXXXX,_XXX____,
  XX_XXXXX,XXXXXXXX,X_XX____,
  X_XXXXXX,XXXXXXXX,X__X____,
  _XXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0031[ 29] = { /* code 0031, DIGIT ONE */
  ____X___,
  ___XX___,
  __XXX___,
  _XXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  _XXXX___,
  ___X____,
  ________,
  ________,
  ___X____,
  __XXX___,
  _XXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  _XXXX___,
  __XXX___,
  ___XX___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0032[ 93] = { /* code 0032, DIGIT TWO */
  _XXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XX_X____,
  ___XXXXX,XXXXXXXX,X_XX____,
  ____XXXX,XXXXXXXX,_XXX____,
  _____XXX,XXXXXXX_,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,________,XXXX____,
  ____XXXX,XXXXXXX_,_XXX____,
  ___XXXXX,XXXXXXXX,__X_____,
  ___XXXXX,XXXXXXXX,X_______,
  _X_XXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXX_,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXX_XXX,XXXXXXX_,________,
  XXX_XXXX,XXXXXXXX,________,
  XX_XXXXX,XXXXXXXX,X_______,
  X_XXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0033[ 93] = { /* code 0033, DIGIT THREE */
  XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,X_X_____,
  __XXXXXX,XXXXXXXX,_XX_____,
  ___XXXXX,XXXXXXX_,XXX_____,
  ____XXXX,XXXXXX_X,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,_______X,XXX_____,
  ___XXXXX,XXXXXX__,_X______,
  __XXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXX_,_X______,
  ___XXXXX,XXXXXX__,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ____XXXX,XXXXXX_X,XXX_____,
  ___XXXXX,XXXXXXX_,XXX_____,
  __XXXXXX,XXXXXXXX,_XX_____,
  _XXXXXXX,XXXXXXXX,X_X_____,
  XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0034[ 87] = { /* code 0034, DIGIT FOUR */
  X_______,________,___X____,
  XX______,________,__XX____,
  XXX_____,________,_XXX____,
  XXXX____,________,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXX____,________,XXXX____,
  _X__XXXX,XXXXXXX_,__X_____,
  ___XXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,__X_____,
  ____XXXX,XXXXXXX_,_XXX____,
  ________,________,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,________,XXXX____,
  ________,________,_XXX____,
  ________,________,__XX____,
  ________,________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0035[ 93] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXXXXXXX,XX______,
  X_XXXXXX,XXXXXXXX,XX______,
  XX_XXXXX,XXXXXXXX,X_______,
  XXX_XXXX,XXXXXXXX,________,
  XXXX_XXX,XXXXXXX_,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXX_,_XXX____,
  ________,________,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  _____XXX,XXXXXXX_,XXXX____,
  ____XXXX,XXXXXXXX,_XXX____,
  ___XXXXX,XXXXXXXX,X_XX____,
  __XXXXXX,XXXXXXXX,X__X____,
  _XXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0036[ 93] = { /* code 0036, DIGIT SIX */
  _XXXXXXX,XXXXXXXX,XX______,
  X_XXXXXX,XXXXXXXX,XX______,
  XX_XXXXX,XXXXXXXX,X_______,
  XXX_XXXX,XXXXXXXX,________,
  XXXX_XXX,XXXXXXX_,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXX____,________,________,
  _X__XXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  _X_XXXXX,XXXXXXXX,__X_____,
  XXXXXXXX,XXXXXXX_,_XXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXX_XXX,XXXXXXX_,XXXX____,
  XXX_XXXX,XXXXXXXX,_XXX____,
  XX_XXXXX,XXXXXXXX,X_XX____,
  X_XXXXXX,XXXXXXXX,X__X____,
  _XXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0037[ 90] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,X_X_____,
  __XXXXXX,XXXXXXXX,_XX_____,
  ___XXXXX,XXXXXXX_,XXX_____,
  ____XXXX,XXXXXX_X,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,_______X,XXX_____,
  ________,________,_X______,
  ________,________,________,
  ________,________,________,
  ________,________,_X______,
  ________,________,XXX_____,
  ________,_______X,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,_______X,XXX_____,
  ________,________,XXX_____,
  ________,________,_XX_____,
  ________,________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0038[ 93] = { /* code 0038, DIGIT EIGHT */
  _XXXXXXX,XXXXXXXX,XX______,
  X_XXXXXX,XXXXXXXX,XX_X____,
  XX_XXXXX,XXXXXXXX,X_XX____,
  XXX_XXXX,XXXXXXXX,_XXX____,
  XXXX_XXX,XXXXXXX_,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXX____,________,XXXX____,
  _X__XXXX,XXXXXXX_,__X_____,
  ___XXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  _X_XXXXX,XXXXXXXX,__X_____,
  XXXXXXXX,XXXXXXX_,_XXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXX_XXX,XXXXXXX_,XXXX____,
  XXX_XXXX,XXXXXXXX,_XXX____,
  XX_XXXXX,XXXXXXXX,X_XX____,
  X_XXXXXX,XXXXXXXX,X__X____,
  _XXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_0039[ 93] = { /* code 0039, DIGIT NINE */
  _XXXXXXX,XXXXXXXX,XX______,
  X_XXXXXX,XXXXXXXX,XX_X____,
  XX_XXXXX,XXXXXXXX,X_XX____,
  XXX_XXXX,XXXXXXXX,_XXX____,
  XXXX_XXX,XXXXXXX_,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXX____,________,XXXX____,
  _X__XXXX,XXXXXXX_,__X_____,
  ___XXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,__X_____,
  ____XXXX,XXXXXXX_,_XXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  _____XXX,XXXXXXX_,XXXX____,
  ____XXXX,XXXXXXXX,_XXX____,
  ___XXXXX,XXXXXXXX,X_XX____,
  __XXXXXX,XXXXXXXX,X__X____,
  _XXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital48_003A[ 26] = { /* code 003A, COLON */
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDSDigital48_CharInfo[12] = {
   {   5,   5,   2,  35,   9, acGUI_FontDSDigital48_002E } /* code 002E, FULL STOP */
  ,{  20,  31,   2,   9,  25, acGUI_FontDSDigital48_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  29,   4,  10,  14, acGUI_FontDSDigital48_0031 } /* code 0031, DIGIT ONE */
  ,{  20,  31,   2,   9,  25, acGUI_FontDSDigital48_0032 } /* code 0032, DIGIT TWO */
  ,{  19,  31,   3,   9,  25, acGUI_FontDSDigital48_0033 } /* code 0033, DIGIT THREE */
  ,{  20,  29,   2,  10,  25, acGUI_FontDSDigital48_0034 } /* code 0034, DIGIT FOUR */
  ,{  20,  31,   2,   9,  25, acGUI_FontDSDigital48_0035 } /* code 0035, DIGIT FIVE */
  ,{  20,  31,   2,   9,  25, acGUI_FontDSDigital48_0036 } /* code 0036, DIGIT SIX */
  ,{  19,  30,   3,   9,  25, acGUI_FontDSDigital48_0037 } /* code 0037, DIGIT SEVEN */
  ,{  20,  31,   2,   9,  25, acGUI_FontDSDigital48_0038 } /* code 0038, DIGIT EIGHT */
  ,{  20,  31,   2,   9,  25, acGUI_FontDSDigital48_0039 } /* code 0039, DIGIT NINE */
  ,{   5,  26,   3,  14,  11, acGUI_FontDSDigital48_003A } /* code 003A, COLON */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital48_Prop2 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontDSDigital48_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital48_Prop1 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDSDigital48_CharInfo[  0] /* address of first character */
  ,&GUI_FontDSDigital48_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital48 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,48 /* height of font  */
  ,48 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDSDigital48_Prop1}
  ,40 /* Baseline */
  ,31 /* Height of lowercase characters */
  ,31 /* Height of capital characters */
};

