/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DS-Digital36.c                                        *
* Font:        DS-Digital                                            *
* Height:      36                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  36                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x25 (37)                                     *
* Character enabled:   0x2E (46)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3B (59)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital36;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0025[ 69] = { /* code 0025, PERCENT SIGN */
  __XXXX__,______XX,X_______,
  __XXXX__,_____XXX,________,
  XX____XX,_____XX_,________,
  XX____XX,____XXX_,________,
  XX____XX,___XXX__,________,
  XX____XX,___XXX__,________,
  XX____XX,__XXX___,________,
  XX____XX,__XX____,________,
  __XXXXX_,_XXX____,________,
  __XXXX__,_XX_____,________,
  ________,________,________,
  ________,X_______,________,
  _______X,XX______,________,
  ______XX,X__XXXXX,________,
  ______XX,__X_XXX_,X_______,
  _____XXX,_XXX___X,XX______,
  ____XXX_,_XXX___X,XX______,
  ____XXX_,_XXX___X,XX______,
  ___XXX__,_XXX___X,XX______,
  ___XXX__,_XXX___X,XX______,
  ___XX___,__X_____,X_______,
  ___X____,___XXXXX,________,
  ________,____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0030[ 48] = { /* code 0030, DIGIT ZERO */
  ________,________,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XX______,_____XXX,
  ________,________,
  XX______,_____XXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0031[ 48] = { /* code 0031, DIGIT ONE */
  _______X,X_______,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  ______XX,X_______,
  ______XX,________,
  ________,________,
  ______XX,________,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0032[ 46] = { /* code 0032, DIGIT TWO */
  _XXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  __XXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXX__,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0033[ 46] = { /* code 0033, DIGIT THREE */
  _XXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0034[ 46] = { /* code 0034, DIGIT FOUR */
  XX______,_____XXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,_____XXX,
  ________,_____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0035[ 46] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXX__,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  __XXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0036[ 46] = { /* code 0036, DIGIT SIX */
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0037[ 48] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,____XXX_,
  ________,________,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,___XXXX_,
  ________,____XXX_,
  ________,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0038[ 48] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  _XXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,_____XXX,
  XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_0039[ 46] = { /* code 0039, DIGIT NINE */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXX_____,____XXXX,
  XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  ________,____XXXX,
  __XXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital36_003A[ 19] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDSDigital36_CharInfo[13] = {
   {  18,  23,   2,   7,  22, acGUI_FontDSDigital36_0025 } /* code 0025, PERCENT SIGN */
  ,{   2,   2,   2,  28,   6, acGUI_FontDSDigital36_002E } /* code 002E, FULL STOP */
  ,{  14,  24,   2,   6,  18, acGUI_FontDSDigital36_0030 } /* code 0030, DIGIT ZERO */
  ,{  14,  23,   2,   7,  18, acGUI_FontDSDigital36_0031 } /* code 0031, DIGIT ONE */
  ,{  14,  23,   2,   7,  18, acGUI_FontDSDigital36_0032 } /* code 0032, DIGIT TWO */
  ,{  13,  23,   2,   7,  18, acGUI_FontDSDigital36_0033 } /* code 0033, DIGIT THREE */
  ,{  14,  23,   2,   7,  18, acGUI_FontDSDigital36_0034 } /* code 0034, DIGIT FOUR */
  ,{  14,  23,   2,   7,  18, acGUI_FontDSDigital36_0035 } /* code 0035, DIGIT FIVE */
  ,{  14,  23,   2,   7,  18, acGUI_FontDSDigital36_0036 } /* code 0036, DIGIT SIX */
  ,{  13,  24,   2,   6,  18, acGUI_FontDSDigital36_0037 } /* code 0037, DIGIT SEVEN */
  ,{  14,  24,   2,   6,  18, acGUI_FontDSDigital36_0038 } /* code 0038, DIGIT EIGHT */
  ,{  14,  23,   2,   7,  18, acGUI_FontDSDigital36_0039 } /* code 0039, DIGIT NINE */
  ,{   2,  19,   2,  11,   8, acGUI_FontDSDigital36_003A } /* code 003A, COLON */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital36_Prop3 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontDSDigital36_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital36_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDSDigital36_CharInfo[  1] /* address of first character */
  ,&GUI_FontDSDigital36_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital36_Prop1 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontDSDigital36_CharInfo[  0] /* address of first character */
  ,&GUI_FontDSDigital36_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital36 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,36 /* height of font  */
  ,36 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDSDigital36_Prop1}
  ,30 /* Baseline */
  ,24 /* Height of lowercase characters */
  ,24 /* Height of capital characters */
};

