/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DS-Digital32.c                                        *
* Font:        DS-Digital                                            *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  32                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3B (59)                                     *
* Character enabled:   0x2E (46)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital32;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_002E[  3] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0030[ 40] = { /* code 0030, DIGIT ZERO */
  _XXXXXXX,XXXX____,
  X_XXXXXX,XXX_X___,
  XX_XXXXX,XX_XX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  _X______,___X____,
  ________,________,
  _X______,___X____,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XX_XXXXX,XX_XX___,
  X_XXXXXX,XXX_X___,
  _XXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0031[ 40] = { /* code 0031, DIGIT ONE */
  _______X,________,
  ______XX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ______X_,________,
  ________,________,
  ______X_,________,
  ______XX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ______XX,________,
  ______XX,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0032[ 40] = { /* code 0032, DIGIT TWO */
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_X___,
  ___XXXXX,XX_XX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  __XXXXXX,XX_XX___,
  __XXXXXX,XXX_____,
  __XXXXXX,XX______,
  XX______,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XX_XXXXX,XX______,
  X_XXXXXX,XXX_____,
  _XXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0033[ 40] = { /* code 0033, DIGIT THREE */
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X__X____,
  ________,__XX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  __XXXXXX,X_X_____,
  _XXXXXXX,XX______,
  __XXXXXX,X_X_____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,__XX____,
  ___XXXXX,X__X____,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0034[ 40] = { /* code 0034, DIGIT FOUR */
  X_______,________,
  XX______,____X___,
  XXX_____,___XX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  _XXXXXXX,XX_X____,
  __XXXXXX,XXX_____,
  __XXXXXX,XX_X____,
  ________,___XX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,___XX___,
  ________,___XX___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0035[ 40] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXXX____,
  X_XXXXXX,XXX_____,
  XX_XXXXX,XX______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,XX______,
  __XXXXXX,XXX_____,
  __XXXXXX,XX______,
  ________,___XX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ___XXXXX,XX_XX___,
  __XXXXXX,XXX_X___,
  _XXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0036[ 40] = { /* code 0036, DIGIT SIX */
  _XXXXXXX,XXXX____,
  X_XXXXXX,XXX_____,
  XX_XXXXX,XX______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  _XXXXXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XX_X____,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XX_XXXXX,XX_XX___,
  X_XXXXXX,XXX_X___,
  _XXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0037[ 40] = { /* code 0037, DIGIT SEVEN */
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X__X____,
  ________,__XX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,__X_____,
  ________,________,
  ________,__X_____,
  ________,__XX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,_XXX____,
  ________,__XX____,
  ________,__XX____,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0038[ 40] = { /* code 0038, DIGIT EIGHT */
  _XXXXXXX,XXXX____,
  X_XXXXXX,XXX_X___,
  XX_XXXXX,XX_XX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  _XXXXXXX,XX_X____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XX_X____,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XX_XXXXX,XX_XX___,
  X_XXXXXX,XXX_X___,
  _XXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_0039[ 40] = { /* code 0039, DIGIT NINE */
  _XXXXXXX,XXXX____,
  X_XXXXXX,XXX_X___,
  XX_XXXXX,XX_XX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  _XXXXXXX,XX_X____,
  __XXXXXX,XXX_____,
  __XXXXXX,XX_X____,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ________,__XXX___,
  ___XXXXX,XX_XX___,
  __XXXXXX,XXX_X___,
  _XXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontDSDigital32_003A[ 17] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontDSDigital32_CharInfo[12] = {
   {   3,   3,   1,  23,   6, acGUI_FontDSDigital32_002E } /* code 002E, FULL STOP */
  ,{  13,  20,   1,   6,  16, acGUI_FontDSDigital32_0030 } /* code 0030, DIGIT ZERO */
  ,{  13,  20,   3,   6,  16, acGUI_FontDSDigital32_0031 } /* code 0031, DIGIT ONE */
  ,{  13,  20,   1,   6,  16, acGUI_FontDSDigital32_0032 } /* code 0032, DIGIT TWO */
  ,{  12,  20,   2,   6,  16, acGUI_FontDSDigital32_0033 } /* code 0033, DIGIT THREE */
  ,{  13,  20,   1,   6,  16, acGUI_FontDSDigital32_0034 } /* code 0034, DIGIT FOUR */
  ,{  13,  20,   1,   6,  16, acGUI_FontDSDigital32_0035 } /* code 0035, DIGIT FIVE */
  ,{  13,  20,   1,   6,  16, acGUI_FontDSDigital32_0036 } /* code 0036, DIGIT SIX */
  ,{  12,  20,   2,   6,  16, acGUI_FontDSDigital32_0037 } /* code 0037, DIGIT SEVEN */
  ,{  13,  20,   1,   6,  16, acGUI_FontDSDigital32_0038 } /* code 0038, DIGIT EIGHT */
  ,{  13,  20,   1,   6,  16, acGUI_FontDSDigital32_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  17,   2,   9,   7, acGUI_FontDSDigital32_003A } /* code 003A, COLON */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital32_Prop2 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontDSDigital32_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontDSDigital32_Prop1 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontDSDigital32_CharInfo[  0] /* address of first character */
  ,&GUI_FontDSDigital32_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontDSDigital32 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,32 /* height of font  */
  ,32 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontDSDigital32_Prop1}
  ,26 /* Baseline */
  ,20 /* Height of lowercase characters */
  ,20 /* Height of capital characters */
};

